### ISSUE TITLE
Read fire variables in WRF NetCDF files with correct dimension

### ISSUE THREAD

**Issue by janmandel** [openwfm/wrfxpy#48]
Fire variables in WRF NetCDF files have dimensions larger by the refinement ratio in both x and y than the domain size, and the strips beyond the end of the domain do not contain valid data. This should be masked in a low-level file interface and hidden from the programmer. 

E.g., with refinement ratio 10 and atmospheric variables size (41,41), the fire variables should be  (410,410) but the NetCDF files have (420,420). The strips indexed from 411 to 420 in i or j have no valid data.

See openwfm/WRF-SFIRE#7 for details.

**Comment by Fergui** [comment]
Done in 891edfd48efeb5f22c4df5240671ff5cb46d6b17
